---
- name: Create backup
  become: true
  archive:
    path: "{{ src_path }}"
    dest: "{{ dest_path }}/{{ansible_date_time.date}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}.tar.gz"
    format: gz
  register: archive_output

- name: Debug archive output
  debug:
    var: archive_output

- name: Find backups
  become: true
  find:
    paths: "{{ dest_path }}"
    patterns: '*.tar.gz'
  register: backups

- name: Debug - Show found backups
  debug:
    var: backups.files
  when: ansible_verbosity >= 4

- name: Sort backups by time
  set_fact:
    sorted_backups: "{{ backups.files | sort(attribute='mtime', reverse=true) }}"

- name: Debug - Show sorted backups
  debug:
    var: sorted_backups
  when: ansible_verbosity >= 4

- name: Delete old backups
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ sorted_backups[max_backups:] }}"
  when: backups.matched > max_backups and delete_old_backups