---
- name: Create backup
  become: true
  command: tar -czf {{ dest_path }}/{{ansible_date_time.date}}-{{ansible_date_time.hour}}{{ansible_date_time.minute}}.tar.gz {{ src_path }}

- name: Find backups
  find:
    paths: "{{ dest_path }}"
    patterns: '*.tar.gz'
  register: backups

- name: Sort backups by time
  set_fact:
    sorted_backups: "{{ backups.files | sort(attribute='mtime', reverse=true) }}"

- name: Delete old backups
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ sorted_backups[max_backups:] }}"
  when: backups.matched > max_backups