---
- name: Environment vars
  block:
  - name: MongoDB User
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_USER' 
      line: 'MONGO_USER={{ project.user }}'
      backrefs: yes

  - name: MongoDB Password
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_PASSWORD' 
      line: 'MONGO_PASSWORD={{ project.user }}'
      backrefs: yes

  - name: MongoDB URI
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_URI' 
      line: 'MONGO_URI=localhost:27017'
      backrefs: yes

  - name: MongoDB Database
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_DB' 
      line: 'MONGO_DB=cat-watcher'
      backrefs: yes

  when: true # Evaluate when .env is needed

- name: Start service
  shell: bash /opt/apps/{{ project.name }}/start.sh {{ project.version }}
  become: true

- name: Wait for service to start
  pause:
    seconds: 15

- name: Show log
  shell: cat /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}.log