---
- name: Database .env vars
  block:
  - name: MongoDB User
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_USER' 
      line: 'MONGO_USER={{ project.user }}'
      backrefs: yes

  - name: MongoDB Password
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_PASSWORD' 
      line: 'MONGO_PASSWORD={{ project.password }}'
      backrefs: yes

  - name: MongoDB URI
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_URI' 
      line: 'MONGO_URI={{ project.uri }}'
      backrefs: yes

  - name: MongoDB Database
    lineinfile: 
      path: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
      regexp: 'MONGO_DB' 
      line: 'MONGO_DB={{ project.database }}'
      backrefs: yes

  when: '{{ project.database }}' != 'null'

- name: Start service
  shell: bash /opt/apps/{{ project.name }}/start.sh {{ project.version }}
  become: true

- name: Wait for service to start
  pause:
    seconds: 15

- name: Show log
  shell: cat /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}.log