---
- name: Write .env file
    template:
      src: env_template.j2
      dest: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
    vars:
      project: project

- name: Start service
  shell: bash /opt/apps/{{ project.name }}/start.sh {{ project.version }}
  become: true

- name: Wait for service to start
  pause:
    seconds: 15

- name: Show log
  shell: cat /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}.log