servers:
  hosts:
    server:
      ansible_host: 192.168.1.55
      ansible_user: jenkins
      ansible_ssh_extra_args: -o StrictHostKeyChecking=accept-new

remote:
  hosts:
    rastberry:
      ansible_host: 192.168.1.44
      ansible_user: jenkins
      ansible_ssh_extra_args: -o StrictHostKeyChecking=accept-new