servers:
  hosts:
    jenkins:
      ansible_host: 192.168.1.55
      ansible_connection: ssh
      ansible_user: jenkins

remote:
  hosts:
    rpi:
      ansible_host: 192.168.1.44
      ansible_connection: ssh
      ansible_user: jenkins