---
- name: Backup Server Files
  hosts: server
  tasks:
    - name: Sync
      synchronize:
        src: "{{ src_path }}"
        dest: /media/devmon/WD_BLACK/NAS/system/backups
        delete: true
      delegate_to: server
      become: true
      remote_user: rdvl

  vars:
    path: src_path