---
- name: Backup Server Files
  hosts: server
  tasks:
    - name: Params
      debug:
        var: path

    - name: Sync
      synchronize:
        src: /DATA/Media
        dest: /media/devmon/WD_BLACK/NAS/system/backups
      delegate_to: server
      become: true
  vars:
    path: path