---
- name: Cleanup
  hosts: servers
  vars:
    status: "Success"
  tasks:
    - block:
        - name: Docker Cleanup
          include_role:
            name: docker-cleanup
      rescue:
        - set_fact:
            status: "Failed"
      always:
        - name: Notify
          include_role:
            name: notify
          vars:
            ansible_task: "Cleanup"
            ansible_task_status: "{{ status }}"
