---
- name: Deploy and Start Service
  hosts: jenkins
  tasks:
    - name: Create directories and clone repository
      shell: >
        mkdir /opt/apps/{{ project.name }}/{{ project.version }} &&
        cd /opt/apps/{{ project.name }}/{{ project.version }} &&
        git clone --depth 1 --branch {{ project.version }} {{ project.url }}

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}