---
- name: Deploy and Start Service
  hosts: jenkins
  tasks:
    - name: Stop service
      command: pm2 stop {{ project.name }}
      become: yes
      ignore_errors: yes

    - name: Check installed versions
      stat:
        path: /opt/apps/{{ project.name }}/{{ project.version }}
      register: installed

    - name: Uninstall version
      shell: rm -rf /opt/apps/{{ project.name }}/{{ project.version }}
      when: installed.stat.exists

    - name: Create directories and clone repository
      shell: >
        mkdir /opt/apps/{{ project.name }}/{{ project.version }} &&
        cd /opt/apps/{{ project.name }}/{{ project.version }} &&
        git clone --depth 1 --branch {{ project.version }} {{ project.url }}

    - name: Install dependencies
      shell: >
        python3 -m venv /opt/apps/{{ project.name }}/{{ project.version }}/venv &&
        . /opt/apps/{{ project.name }}/{{ project.version }}/venv/bin/activate &&
        pip3 install -r /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/requirements.txt

    - name: Write .env file
      vars:
        env_content: |
          MONGO_USER={{ project.user }}
          MONGO_PASSWORD={{ project.password }}
          MONGO_URI=localhost:27017
          MONGO_DB=cat-watcher
      copy:
        content: "{{ env_content }}"
        dest: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/.env
        mode: '0644'

    - name: Start service
      shell: bash /opt/apps/{{ project.name }}/start.sh {{ project.version }}
      become: yes

    - name: Wait for service to start
      pause:
        seconds: 15

    - name: Show log
      shell: cat /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}.log