---
- name: Deploy and Start Service
  hosts: jenkins
  roles:
    - role: pre_install
      vars:
        project: project

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}

    - role: post_install
      vars:
        project: project
