---
- name: Deploy and Start Service
  hosts: jenkins
  tasks:
    - name: Pre install
      import_role:
        name: pre_install
      vars:
        project: project

    - name: Install dependencies
      shell: >
        python3 -m venv /opt/apps/{{ project.name }}/{{ project.version }}/venv &&
        . /opt/apps/{{ project.name }}/{{ project.version }}/venv/bin/activate &&
        pip3 install -r /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}/requirements.txt

    - name: Post install
      import_role:
        name: post_install
      vars:
        project: project