---
- name: Deploy and Start Service
  hosts: jenkins
  tasks:
    - name: Pre install
      import_role:
        name: pre_install
      vars:
        project: project

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /opt/apps/{{ project.name }}/{{ project.version }}/{{ project.name }}

    - name: Post install
      import_role:
        name: post_install
      vars:
        project: project