---
- name: Docker cleanup
  hosts: all
  tasks:
    - name: Docker Prune
      become: true
      docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true