---
- name: Hello World!
  hosts: all
  vars:
    status: "Success"
  tasks:
    - block:
        - name: Hello World!
          debug:
            msg: "Hello World!"
      rescue:
        - set_fact:
            status: "Failed"
      always:
        - name: Notify
          include_role:
            name: notify
          vars:
            ansible_task: "Helo World"
            ansible_task_status: "{{ status }}"