---
- name: Sync Folder
  hosts: "{{ host }}"
  tasks:
    - name: Sync
      synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        delete: true
        perms: false
        owner: false
        group: false
        links: false
      delegate_to: "{{ host }}"
      become: true

  vars:
    host: host
    src_path: src_path
    dest_path: dest_path
