---
- name: Sync Server Folder
  hosts: server
  tasks:
    - name: Sync
      synchronize:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        delete: true
        perms: false
        owner: false
        group: false
        links: false
      delegate_to: server
      become: true

  vars:
    src_path: src_path
    dest_path: dest_path
