---
- name: Sync Server Folder
  hosts: server
  tasks:
    - name: Sync
      synchronize:
        src: "{{ src_path }}"
        dest: /media/devmon/WD_BLACK/NAS/system/backups
        delete: true
        perms: false
        owner: false
        group: false
      delegate_to: server
      become: true

  vars:
    path: src_path