---
- name: Update host
  hosts: all
  tasks:
    - name: Update and upgrade
      become: yes
      apt:
        update_cache: true
        upgrade: 'yes'
        register: apt_get_status
        until: apt_get_status is success
        retries: 60
        delay: 10