---
- name: Update host
  hosts: all

  tasks:
    - name: Update and upgrade
      become: true
      apt:
        update_cache: true
        upgrade: 'yes'
        lock_timeout: 240

    - name: Cleanup
      become: true
      apt:
        clean: true
        autoremove: true