---
- name: Server Update
  hosts: servers
  vars:
    status: "Success"
  tasks:
    - block:
        - name: Update
          include_role:
            name: update

        - name: Reboot
          include_role:
            name: reboot
      rescue:
        - set_fact:
            status: "Failed"
      always:
        - name: Notify
          include_role:
            name: notify
          vars:
            ansible_task: "Server Update"
            ansible_task_status: "{{ status }}"